name: Deploy to Aws Docker on merge
'on':
  push:
    branches:
      - prod
jobs:
  docker:
    runs-on: ubuntu-latest    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: atom4real/se331-2022-project--frontend:latest
      - name: prepare the docker-compose run
        run: |    
          mkdir se331-2022-project--frontend       
          cp docker-compose.yml se331-2022-project--frontend/docker-compose.yml        
          cd se331-2022-project--frontend        
          docker-compose -H ${{ secrets.HOST_SERVER }} down          
          docker-compose -H ${{ secrets.HOST_SERVER }} pull
          docker-compose -H ${{ secrets.HOST_SERVER }} up -d